name: Huntbook
options:
  bundleIdPrefix: com.shimondeitel.huntbook
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "4"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Huntbook:
    type: application
    platform: iOS
    sources:
      - path: Huntbook
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.huntbook
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Huntbook/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  HuntbookTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: HuntbookTests
      - path: Huntbook.storekit
    dependencies:
      - target: Huntbook
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.huntbook.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  HuntbookUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: HuntbookUITests
    dependencies:
      - target: Huntbook
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.huntbook.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Huntbook:
    build:
      targets:
        Huntbook: all
        HuntbookTests: [test]
        HuntbookUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Huntbook.storekit
    test:
      config: Debug
      storeKitConfiguration: Huntbook.storekit
      targets:
        - HuntbookTests
        - HuntbookUITests
    archive:
      config: Release
